web: gunicorn alx_recruitment_tracker.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --timeout 120
worker: python -m celery -A alx_recruitment_tracker worker -l info --pool=solo
beat: python -m celery -A alx_recruitment_tracker beat -l info
