# Generated by Django 5.2.5 on 2025-08-18 18:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_service', '0002_audit_log_officer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfficerCampaignAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officer_assignments', to='dashboard_service.campaign')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_assignments', to='auth_service.officer')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_link', models.URLField()),
                ('ref_code', models.CharField(max_length=300, unique=True)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('signup_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('revoke_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_links', to='dashboard_service.campaign')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_links', to='auth_service.officer')),
            ],
        ),
        migrations.CreateModel(
            name='DailyMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_date', models.DateField()),
                ('total_clicks', models.PositiveIntegerField(default=0)),
                ('total_signups', models.PositiveIntegerField(default=0)),
                ('click_to_signup_rate', models.FloatField(default=0.0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='dashboard_service.campaign')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='auth_service.officer')),
                ('referral_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='dashboard_service.referrallink')),
            ],
        ),
    ]
