# Generated by Django 5.2.5 on 2025-08-18 19:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudFindings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('click', 'ClickEvent'), ('signup', 'SignupEvent')], max_length=50)),
                ('event_id', models.UUIDField()),
                ('fraud_score', models.FloatField(default=0.0)),
                ('findings_details', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512, null=True)),
                ('geo_country', models.CharField(blank=True, max_length=64, null=True)),
                ('geo_city', models.CharField(blank=True, max_length=64, null=True)),
                ('geo_region', models.CharField(blank=True, max_length=64, null=True)),
                ('fraud_score', models.FloatField(default=0.0)),
                ('referral_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_events', to='dashboard_service.referrallink')),
            ],
        ),
        migrations.CreateModel(
            name='SignupEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversion_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('fraud_score', models.FloatField(default=0.0)),
                ('click_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signup_events', to='tracking_service.clickevent')),
                ('referral_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signup_events', to='dashboard_service.referrallink')),
            ],
        ),
    ]
